package com.myteam.test_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pojo2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pojo2() {
    }

asdfasdf


}